package lusql.parser;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;

/**
 * The parser's contract. These tests are the specification: when one is red, the SOURCE is wrong.
 * Do not edit this file to make it pass.
 */
class ParserTest {

    @Test
    void parsesSelectStar() {
        Select select = Parser.parse("SELECT * FROM t");

        assertEquals(List.of("*"), select.columns());
        assertEquals("t", select.table());
        assertEquals(Optional.empty(), select.where());
    }

    @Test
    void parsesWhereClause() {
        Select select = Parser.parse("SELECT * FROM t WHERE x = 1");

        assertTrue(select.where().isPresent(), "the WHERE clause should be parsed");
        assertEquals(new Expr.Comparison("x", "=", "1"), select.where().get());
    }
}
